"""create user table

Revision ID: 1cd48b9a3a60
Revises: 9afc003fa50e
Create Date: 2023-04-28 14:06:53.683165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd48b9a3a60'
down_revision = '9afc003fa50e'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        'users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String(255), nullable=False),
        sa.Column('email', sa.String(255), nullable=False),
        sa.Column('password', sa.String(255), nullable=False),
        sa.UniqueConstraint('username', name='uq_username'),
        sa.UniqueConstraint('email', name='uq_email')
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
